docs: gsoc'23 final report - improve development experience
CircuitVerse/Blog pull request #177
Opened 2023-08-27 20:32 UTC by tanmoysrt

2023-08-29 08:40 UTC, vedant-jain03 requested changes
can you please compress the video

2023-08-29 08:45 UTC, tanmoysrt commented
> can you please compress the video

Sure !

2023-08-29 09:04 UTC, tanmoysrt commented
@vedant-jain03 compressed the videos .

2023-08-30 10:09 UTC, vedant-jain03 requested changes
just a few comments

2023-08-30 10:09 UTC, vedant-jain03 commented on content/posts/Tanmoy_Sarkar_Final_Report.md
> +Throught this period, we have focused on improving the development experience of CircuitVerse. The main goals of this project are:
```suggestion
Throughout this period, we have focused on improving the development experience of CircuitVerse. The main goals of this project are:
```

2023-08-30 10:09 UTC, vedant-jain03 commented on content/posts/Tanmoy_Sarkar_Final_Report.md
> +This integration also supports Docker-based environments, allowing the application to be run in a Docker container while connecting the IDE/Editor's solargraph extension to the Solargraph server via
```suggestion
This integration also supports Docker-based environment, allowing the application to be run in a Docker container while connecting the IDE/Editor's solargraph extension to the Solargraph server via a TCP socket. Initially, there was a significant challenge in this setup. The extension was used to send the current directory to the LSP server, but the LSP server had a different path inside the Docker container. However, this issue was successfully resolved by creating a symlink inside the container. 
```

2023-08-30 10:11 UTC, tanmoysrt commented on content/posts/Tanmoy_Sarkar_Final_Report.md
> +This blog is dedicated to describe the work we have done and the goals we have accomplished in Google Summer of Code'23.
updated !

2023-08-30 10:54 UTC, vedant-jain03 approved these changes

2023-08-30 10:54 UTC, merged