feat: development of vue simulator final report
CircuitVerse/Blog pull request #181
Opened 2023-09-07 20:47 UTC by Arnabdaz

- Added final report for GSoC@23 project Development of Vue Simulator.

2023-09-08 03:22 UTC, Arnabdaz commented
cc @vedant-jain03 @devartstar

2023-09-11 05:11 UTC, vedant-jain03 requested changes

2023-09-11 05:11 UTC, vedant-jain03 commented on content/posts/Arnab_Das_GSoC_final_report.md
> +4. implementation of JWT for Vue Simulator
```suggestion
4. Implementation of JWT for Vue Simulator
```

2023-09-11 05:11 UTC, vedant-jain03 commented on content/posts/Arnab_Das_GSoC_final_report.md
> +1. moving the tab related data (e.g. tabs info, active tabs etc.) to be stored on Pinia Store.
```suggestion
1. Moving the tab related data (e.g. tabs info, active tabs etc.) to be stored on Pinia Store.
```

2023-09-11 05:11 UTC, vedant-jain03 commented on content/posts/Arnab_Das_GSoC_final_report.md
> +we used modern ES6 JavaScript to implement the dragging functionality. After some research and testing, we decided to use [interact.js](https://github.com/taye/interact.js). The main reason behind us
```suggestion
We used modern ES6 JavaScript to implement the dragging functionality. After some research and testing, we decided to use [interact.js](https://github.com/taye/interact.js). The main reason behind using this library was its small size, similar usage to jQueryUI, nearest internal implementation if it was to be implemented from scratch and most importantly it provided all the functionality needed for the simulator.
```

2023-09-11 05:11 UTC, vedant-jain03 commented on content/posts/Arnab_Das_GSoC_final_report.md
> +Embed view provides a preview of the circuit which, in which one can't edit the circuit. this also, allows users to embed the circuit in external websites. This was implemented by creating a new rout
```suggestion
Embed view provides a preview of the circuit, in which one can't edit the circuit. This also, allows users to embed the circuit in external websites. This was implemented by creating a new route `/simualtorvue/embed/:id` which would render the embed view of the circuit.
```

2023-09-11 05:11 UTC, vedant-jain03 commented on content/posts/Arnab_Das_GSoC_final_report.md
> +- currently the simulator is working totally fine only few functionalities have some bugs , so most important point would be fixing those to make the simulator fully ready to replace the current one.
```suggestion
- Currently, the simulator is working totally fine only a few functionalities have some bugs, so the most important point would be fixing those to make the simulator fully ready to replace the current one.
```

2023-09-11 05:13 UTC, vedant-jain03 approved these changes
Merging this, @Arnabdaz Great work, and thankyou for your contribution. 🎉 🚀 

cc @devartstar @tachyons

2023-09-11 05:13 UTC, merged