fir: #205 - Changed the footer year
CircuitVerse/Blog pull request #206
Opened 2024-01-23 20:29 UTC by subhamkumarr

Changed footer copyright year from `2023` to `2024`

2024-01-23 20:36 UTC, subhamkumarr commented
I have raised PR  @tanmoysrt @VaibhavUpreti
could you please review my PR

2024-01-24 11:01 UTC, tanmoysrt requested changes

2024-01-24 11:01 UTC, tanmoysrt commented on content/posts/my_new_post.md
> +
Remove this

2024-01-24 13:06 UTC, tanmoysrt commented
Usually you can do changes and push in the same branch, you don't need to raise new PR everytime you make changes. As you have created #207 already, I am closing this one.

2024-01-24 13:06 UTC, closed without merging