phase-1 blog
CircuitVerse/Blog pull request #218
Opened 2024-07-10 16:16 UTC by jaydip1235

Blog of Phase 1

2024-07-11 15:40 UTC, tanmoysrt requested changes

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +    ```
Avoid adding code snippets to this blog, until unless it's too important.
ig All sort of these things are present in your personal blog. Adding link to that blog or code snippet will be better way.

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +    ```
Same for all the code snippets in the blog @jaydip1235

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +    ```
You may add gif or video of the feature in the blog also to showcase a ppreview of the feature.

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +* Creating controllers, schemas and tables for all the use case [Week 1 to 3]
```suggestion
* Creating controllers, schemas and tables for circuitverse practice section [Week 1 to 3]
```

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +* Moderator Question Creation and Integration[Week 5 to 6]
Integration with Simulator ?

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +During the community bonding period for GSoC at CircuitVerse, we engaged in various activities to prepare for the project. We began by participating in meet-and-greet sessions with mentors, contribut
```suggestion
During the community bonding period for GSoC at CircuitVerse, there were various activities to provide more context for the project. The project begins with a meet-and-greet sessions with mentors, contributors, and admins, where everyone shared their excitement for GSoC, discussed their journeys, and discuessed about the projects. Mentors [Vaibhav Upreti](https://www.linkedin.com/in/vaibhav-upreti/), [Vedant Jain](https://www.linkedin.com/in/vedant-jain-781006145/), and [Tanmoy Sarkar](https://www.linkedin.com/in/tanmoysrt/), answered questions about the CircuitVerse Practice Section project, and [Aboobacker MK](https://www.linkedin.com/in/aboobacker-m-k/) provided insights into the 12-week project process and discussed open defects in CircuitVerse.
```

You can add a context about `open defects in CircuitVerse`

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +We then focused on a detailed exploration of the CircuitVerse codebase, identifying areas for modification and making initial changes. we had in-depth discussions with [Ruturaj Mohite](https://www.li
```suggestion
Then, the focus got shifted to detailed exploration of the CircuitVerse codebase, identifying areas for modification and making initial changes. we had in-depth discussions with [Ruturaj Mohite](https://www.linkedin.com/in/ruturaj-mohite/), about potential edge cases and the development of the question practice simulator versus the standard simulator, including how to track and save user progress.
```

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +Pull request for phase 1 can be found [here](https://github.com/CircuitVerse/CircuitVerse/pull/5015)
This PR https://github.com/CircuitVerse/CircuitVerse/pull/4967 should be added in the list also.

2024-07-11 15:40 UTC, tanmoysrt commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +The tasks to be done include developing the UI for the moderators dashboard and integrating it with the backend to enable CRUD operations on questions. Next, efforts will focus on making the question
It will be better if you can write this things in bullet points.

2024-07-11 16:36 UTC, jaydip1235 commented
@tanmoysrt made the changes. Please have a look

2024-07-14 18:06 UTC, VaibhavUpreti commented on content/posts/Jaydip_Dey_Phase_1_Report.md
> +- PR : [Addig moderators and questions with simulator integration](https://github.com/CircuitVerse/CircuitVerse/pull/5015)
```suggestion
- PR : [Adding moderators and questions with simulator integration](https://github.com/CircuitVerse/CircuitVerse/pull/5015)
```

2024-07-14 19:32 UTC, jaydip1235 commented
@VaibhavUpreti corrected the spelling

2024-07-14 22:39 UTC, VaibhavUpreti approved these changes

2024-07-14 22:51 UTC, merged