feat: add blog phase 1 report Aman Asrani
CircuitVerse/Blog pull request #221
Opened 2024-07-12 02:37 UTC by Asrani-Aman

Enhancing CircuitVerse User Experience | GSOC2024 | Phase 1 Report

2024-07-20 17:23 UTC, vedant-jain03 requested changes
@Asrani-Aman Looks good, added some comments, PTAL

2024-07-20 17:23 UTC, vedant-jain03 commented on content/posts/Aman_Asrani_phase_1_report_Enhancing_Circuitverse_User_Experiance_GSOC2024.md
> +I initially encountered a number of problems some of which are because of gem `devise-saml-authenticable` and  gem `ruby-saml` versioning compatibility. Finally,  I was able to redirect to the OKTA l
@Asrani-Aman Let's use "we" rather than "I", this applies to all content.
This blog is from our as a project team side to the community.

2024-07-20 17:23 UTC, vedant-jain03 commented on content/posts/Aman_Asrani_phase_1_report_Enhancing_Circuitverse_User_Experiance_GSOC2024.md
> +Currently, CircuitVerse doesn’t verify users’ emails during registration, so we need to implement email verification at that time. Initially, I used Sendrik as the email service, but then I get to kn
```suggestion
Currently, CircuitVerse doesn’t verify user's emails during registration, so we need to implement email verification at that time. Initially, I used Sendrik as the email service, but then I get to know that CircuitVerse already has access to AWS. So, I switched to using AWS SES (Simple Email Service) to send confirmation emails.
```

And above comment

2024-07-20 17:23 UTC, vedant-jain03 commented on static/images/Aman_Asrani/sso.mp4
This would be heavy file, please compress this

2024-07-20 17:23 UTC, vedant-jain03 commented on static/images/Aman_Asrani/Proposed Method for Email Verifiacation of Existing User.mp4
Compress this file

2024-07-20 17:23 UTC, vedant-jain03 commented on static/images/Aman_Asrani/Email Verification using Devise Confirmable.mp4
compress this file

2024-07-21 04:22 UTC, Arnabdaz requested changes
let's not use spaces in file names as we don't know which platforms and browsers the viewers gonna use.
you can use Snake case or Camel case for naming the files

2024-08-02 16:52 UTC, Asrani-Aman commented
Hello @vedant-jain03,

Yes, I understand that video files are large, but these files are already compressed. Do I need to compress them further?

2024-08-02 17:18 UTC, Asrani-Aman commented on content/posts/Aman_Asrani_phase_1_report_Enhancing_Circuitverse_User_Experiance_GSOC2024.md
> +I initially encountered a number of problems some of which are because of gem `devise-saml-authenticable` and  gem `ruby-saml` versioning compatibility. Finally,  I was able to redirect to the OKTA l
I am really sorry, I shouldn't use "I"

2024-08-03 09:02 UTC, Asrani-Aman commented
@vedant-jain03 @Arnabdaz done changes

2024-08-03 09:04 UTC, Asrani-Aman commented
@vedant-jain03 @Arnabdaz done changes

2024-08-25 17:06 UTC, vedant-jain03 approved these changes

2024-08-25 17:07 UTC, merged