fead: add Aman_Asrani_gsoc24_final_report
CircuitVerse/Blog pull request #225
Opened 2024-08-27 14:37 UTC by Asrani-Aman

2024-08-27 14:47 UTC, Asrani-Aman commented
@vedant-jain03 @smritigarg @Arnabdaz ,

Here is the Final report can you please review this?

2024-08-30 14:58 UTC, vedant-jain03 requested changes

2024-08-30 14:58 UTC, vedant-jain03 commented on content/posts/Aman_Asrani_gsoc24_final_report.md
> +We initially encountered a number of problems, some of which were due to gem devise-saml-authenticable and gem ruby-saml versioning compatibility. Finally, we were able to redirect to the Identity Pr
```suggestion
We initially encountered a number of problems, some of which were due to gem devise-saml-authenticable and gem ruby-saml versioning compatibility. Finally, we were able to redirect to the Identity Provider(IDP) login page and obtain the SAML answer after addressing these issues. However, we then ran into a problem while trying to sign the user, which took too much time. During a meeting with Tanmoy, we discovered that the create method in the saml_sessions_controller was being overridden by the create method from the devise_saml_authenticable gem. Finally, SAML-based SSO worked smoothly.
```

It's a formal blog!

2024-08-30 14:58 UTC, vedant-jain03 commented on content/posts/Aman_Asrani_gsoc24_final_report.md
> +Initially, We had considered setting up a Git Hook. However, this approach would likely requirestoring the logs in our database, which is an expensive task.
```suggestion
Initially, We had considered setting up a Git Hook. However, this approach requires storing the logs in our database, which is expensive.
```

2024-09-01 03:39 UTC, vedant-jain03 approved these changes

2024-09-01 03:46 UTC, merged